"""empty message

Revision ID: 08e6ef966556
Revises: fe2267333895
Create Date: 2023-03-29 13:59:54.228933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08e6ef966556'
down_revision = 'fe2267333895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccfdatacomplete',
    sa.Column('apogeeID', sa.String(), nullable=False),
    sa.Column('nvisits', sa.Integer(), nullable=True),
    sa.Column('mjd', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('ccf', sa.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('apogeeID')
    )
    op.drop_table('ccfdata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccfdata',
    sa.Column('apogeeID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nvisits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mjd', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('ccf', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('apogeeID', name='ccfdata_pkey')
    )
    op.drop_table('ccfdatacomplete')
    # ### end Alembic commands ###
