"""empty message

Revision ID: 8079cf20b172
Revises: 
Create Date: 2023-04-05 21:32:59.746143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8079cf20b172'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binaryfinal',
    sa.Column('temp_col', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('mjd', sa.Integer(), nullable=True),
    sa.Column('apogeeID', sa.String(), nullable=True),
    sa.Column('fluxa', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('wavelengtha', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('fluxb', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('wavelengthb', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('fluxc', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('wavelengthc', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('ampa', sa.Float(), nullable=True),
    sa.Column('vhelioa', sa.Float(), nullable=True),
    sa.Column('fwhma', sa.Float(), nullable=True),
    sa.Column('ampb', sa.Float(), nullable=True),
    sa.Column('vheliob', sa.Float(), nullable=True),
    sa.Column('fwhmb', sa.Float(), nullable=True),
    sa.Column('SNR', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('temp_col')
    )
    op.drop_table('binarytable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binarytable',
    sa.Column('temp_col', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mjd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('apogeeID', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fluxa', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('wavelengtha', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('fluxb', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('wavelengthb', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('fluxc', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('wavelengthc', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('ampa', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vhelioa', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fwhma', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ampb', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vheliob', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fwhmb', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SNR', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('temp_col', name='binarytable_pkey')
    )
    op.drop_table('binaryfinal')
    # ### end Alembic commands ###
