"""empty message

Revision ID: d640c246aacc
Revises: 8079cf20b172
Create Date: 2023-04-06 23:59:48.074980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd640c246aacc'
down_revision = '8079cf20b172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccfdata',
    sa.Column('apogeeID', sa.String(), nullable=False),
    sa.Column('nvisits', sa.Integer(), nullable=True),
    sa.Column('mjd', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('ccf', sa.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('apogeeID')
    )
    op.drop_table('ccfdatacomplete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccfdatacomplete',
    sa.Column('apogeeID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nvisits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mjd', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('ccf', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('apogeeID', name='ccfdatacomplete_pkey')
    )
    op.drop_table('ccfdata')
    # ### end Alembic commands ###
