"""empty message

Revision ID: d6f91ac1e960
Revises: 
Create Date: 2023-02-27 15:07:22.242233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f91ac1e960'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binarysystem',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mjd', sa.Integer(), nullable=True),
    sa.Column('apogeeID', sa.String(), nullable=True),
    sa.Column('visitno', sa.Integer(), nullable=True),
    sa.Column('fluxa', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('wavelengtha', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('fluxb', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('wavelengthb', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('fluxc', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('wavelengthc', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('ampa', sa.Float(), nullable=True),
    sa.Column('vhelioa', sa.Float(), nullable=True),
    sa.Column('fwhma', sa.Float(), nullable=True),
    sa.Column('ampb', sa.Float(), nullable=True),
    sa.Column('vheliob', sa.Float(), nullable=True),
    sa.Column('fwhmb', sa.Float(), nullable=True),
    sa.Column('SNR', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('binarysystem')
    # ### end Alembic commands ###
